import os
import time
import gradio as gr
from src.backend.database import add_history_entry

# Placeholder for actual Google Cloud imports
# from google.cloud import documentai
# import google.generativeai as genai

# Configuration for Gemini 3.0 (Mock constant)
GEMINI_MODEL = "gemini-3.0-pro-001"

def phase1_process_files(files, username, progress=gr.Progress()):
    if not files: return "No files.", [], None
    
    progress(0.1, desc="[Phase 1] Uploading to GCS...")
    time.sleep(1)
    progress(0.5, desc="[Phase 1] Document AI processing...")
    time.sleep(1)
    
    file_list = [f.name.split('\\')[-1] for f in files]
    output_msg = f"Processed {len(files)} files via Document AI."
    
    # Log to History
    add_history_entry(username, "Digital Capture", "Success", f"Processed {len(files)} docs")
    
    return output_msg, file_list, "ready"

def phase2_generate_outline(topic, prev_status, username, progress=gr.Progress()):
    progress(0.3, desc=f"Querying {GEMINI_MODEL}...")
    time.sleep(1.5)
    
    outline = f"# Thesis: {topic}\n\nGenerated by {GEMINI_MODEL}\n1. Introduction..."
    
    add_history_entry(username, "Outline Generation", "Success", f"Topic: {topic}")
    return outline

def phase3_write_content(chapter, outline, instr, username, progress=gr.Progress()):
    progress(0.5, desc=f"Writing with {GEMINI_MODEL} & RAG...")
    time.sleep(2)
    
    content = f"# {chapter}\n\nDraft content by {GEMINI_MODEL}...\nBased on instructions: {instr}"
    
    add_history_entry(username, "Drafting Chapter", "Success", f"Chapter: {chapter}")
    return content

def phase4_evaluate_and_export(content, username, progress=gr.Progress()):
    progress(0.5, desc="Verifying Groundedness...")
    time.sleep(1)
    
    filename = f"Thesis_Final_{int(time.time())}.docx"
    with open(filename, "w") as f: f.write(content)
    
    report = "Vertex AI Eval: Groundedness 0.98"
    add_history_entry(username, "Export & Eval", "Success", f"File: {filename}")
    
    return report, filename
